export enum UserStatusEnum {
	ACTIVE = 'ACTIVE',
	DELETED = 'DELETED',
	LIMITED = 'LIMITED',
	LIMITED_DELETED = 'LIMITED_DELETED',
	NOT_REGISTERED = 'NOT_REGISTERED',
	PENDING_EMAIL_VERIFICATION = 'PENDING_EMAIL_VERIFICATION',
}
